### PR TITLE
Ember cli examplar failing tests

### PR DESCRIPTION
**Pull request by bantic**
@mixonic for you

After reviewing the Emblem docs and the open issues relating to line breaks and whitespace, I think we had a few of these tests written to expect incorrect behavior. In short, there should be almost no linebreaks in text output. Example

```
// emblem
span
   hello there,
   how are you
```

becomes

```
<span>hello there, how are you</span>
```

according to the emblem docs, but we have some tests that are incorrectly asserting that the newlines are in the output.

I added some failing tests to capture the correct expected behavior here.

image

### CODE REVIEW

**Comment by mixonic** [comment]
@machty are we on the right track here? Seems sane to me.

**Comment by bantic** [comment]
@machty Yeah — any gotchas we should know about how Emblem handles whitespace? I.e. when to ensure newlines are in the output and when they get swallowed?

**Comment by bantic** [comment]
(also, apologies for combining these two commits — half the diffs are just me moving text in files around). There are no new tests here, I don't think, just changing the expected output of a couple to remove some "\n"s.

**Comment by bantic** [comment]
Ah — nevermind, tests 1,2,3 above are new.

**Comment by machty** [comment]
Your test cases seem correct. To my knowledge emblem never adds newlines. I can understand the reasoning but I haven't heard anyone complain about the present day behavior but I'd be open to changing that if there were a relevant issue.

**Pull request merged**
